[2024-10-26T06:09:16.182+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T06:09:16.196+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T06:09:13.938106+00:00 [queued]>
[2024-10-26T06:09:16.199+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T06:09:13.938106+00:00 [queued]>
[2024-10-26T06:09:16.200+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T06:09:16.208+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_from_gcp> on 2024-10-26 06:09:13.938106+00:00
[2024-10-26T06:09:16.215+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T06:09:16.216+0000] {standard_task_runner.py:63} INFO - Started process 107 to run task
[2024-10-26T06:09:16.217+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'download_data_from_gcp', 'manual__2024-10-26T06:09:13.938106+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpndjrn574']
[2024-10-26T06:09:16.218+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask download_data_from_gcp
[2024-10-26T06:09:16.243+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T06:09:13.938106+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T06:09:16.279+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='download_data_from_gcp' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T06:09:13.938106+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T06:09:13.938106+00:00'
[2024-10-26T06:09:16.283+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T06:09:16.306+0000] {DownloadData.py:31} INFO - Starting data download process
[2024-10-26T06:09:16.306+0000] {DownloadData.py:32} INFO - Starting data download process
[2024-10-26T06:09:16.310+0000] {DownloadData.py:34} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T06:09:16.310+0000] {DownloadData.py:35} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T06:09:16.311+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T06:09:16.311+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T06:09:16.321+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=download_data_from_gcp, run_id=manual__2024-10-26T06:09:13.938106+00:00, execution_date=20241026T060913, start_date=20241026T060916, end_date=20241026T060916
[2024-10-26T06:09:16.357+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T06:09:16.369+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T06:09:16.373+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
