[2024-10-26T22:12:43.260+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T22:11:59.571015+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
