[2024-10-22T22:22:14.968+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-22T22:22:14.983+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.load_data_task manual__2024-10-22T22:22:10.471572+00:00 [queued]>
[2024-10-22T22:22:14.989+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.load_data_task manual__2024-10-22T22:22:10.471572+00:00 [queued]>
[2024-10-22T22:22:14.991+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-22T22:22:15.000+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_task> on 2024-10-22 22:22:10.471572+00:00
[2024-10-22T22:22:15.006+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=73) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-22T22:22:15.006+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'load_data_task', 'manual__2024-10-22T22:22:10.471572+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpgbt_e8ir']
[2024-10-22T22:22:15.008+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask load_data_task
[2024-10-22T22:22:15.008+0000] {standard_task_runner.py:63} INFO - Started process 75 to run task
[2024-10-22T22:22:15.039+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.load_data_task manual__2024-10-22T22:22:10.471572+00:00 [running]> on host fdb7b15dd7ea
[2024-10-22T22:22:15.099+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='load_data_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T22:22:10.471572+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T22:22:10.471572+00:00'
[2024-10-22T22:22:15.100+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-22T22:22:15.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-22T22:22:15.111+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_data() missing 1 required positional argument: 'pickled_file_path'
[2024-10-22T22:22:15.117+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=DataPipeline, task_id=load_data_task, run_id=manual__2024-10-22T22:22:10.471572+00:00, execution_date=20241022T222210, start_date=20241022T222214, end_date=20241022T222215
[2024-10-22T22:22:15.125+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task load_data_task (load_data() missing 1 required positional argument: 'pickled_file_path'; 75)
[2024-10-22T22:22:15.143+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-22T22:22:15.153+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T22:22:15.155+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
