[2024-10-26T09:12:46.520+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T09:12:46.530+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T09:12:45.197328+00:00 [queued]>
[2024-10-26T09:12:46.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T09:12:45.197328+00:00 [queued]>
[2024-10-26T09:12:46.534+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T09:12:46.540+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_from_gcp> on 2024-10-26 09:12:45.197328+00:00
[2024-10-26T09:12:46.544+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=125) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T09:12:46.546+0000] {standard_task_runner.py:63} INFO - Started process 127 to run task
[2024-10-26T09:12:46.546+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'download_data_from_gcp', 'manual__2024-10-26T09:12:45.197328+00:00', '--job-id', '167', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmph7v_g5dz']
[2024-10-26T09:12:46.548+0000] {standard_task_runner.py:91} INFO - Job 167: Subtask download_data_from_gcp
[2024-10-26T09:12:46.595+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T09:12:45.197328+00:00 [running]> on host 558a41ea7330
[2024-10-26T09:12:46.635+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='download_data_from_gcp' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T09:12:45.197328+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T09:12:45.197328+00:00'
[2024-10-26T09:12:46.636+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T09:12:46.642+0000] {DownloadData.py:31} INFO - Starting data download process
[2024-10-26T09:12:46.643+0000] {DownloadData.py:32} INFO - Starting data download process
[2024-10-26T09:12:46.645+0000] {DownloadData.py:34} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T09:12:46.645+0000] {DownloadData.py:35} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T09:12:46.645+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T09:12:46.645+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T09:12:46.649+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=download_data_from_gcp, run_id=manual__2024-10-26T09:12:45.197328+00:00, execution_date=20241026T091245, start_date=20241026T091246, end_date=20241026T091246
[2024-10-26T09:12:46.686+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T09:12:46.701+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T09:12:46.701+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
