[2024-10-23T19:56:24.312+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-23T19:56:24.330+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.process_data manual__2024-10-23T19:56:17.472720+00:00 [queued]>
[2024-10-23T19:56:24.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.process_data manual__2024-10-23T19:56:17.472720+00:00 [queued]>
[2024-10-23T19:56:24.338+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-23T19:56:24.348+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_data> on 2024-10-23 19:56:17.472720+00:00
[2024-10-23T19:56:24.355+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3521) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-23T19:56:24.356+0000] {standard_task_runner.py:63} INFO - Started process 3523 to run task
[2024-10-23T19:56:24.356+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'process_data', 'manual__2024-10-23T19:56:17.472720+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpgecnqrfc']
[2024-10-23T19:56:24.358+0000] {standard_task_runner.py:91} INFO - Job 93: Subtask process_data
[2024-10-23T19:56:24.397+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.process_data manual__2024-10-23T19:56:17.472720+00:00 [running]> on host 6c58daef65ee
[2024-10-23T19:56:24.470+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T19:56:17.472720+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T19:56:17.472720+00:00'
[2024-10-23T19:56:24.472+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-23T19:56:24.488+0000] {HandlingNullValues.py:24} INFO - Loading CSV data for processing
[2024-10-23T19:56:24.559+0000] {HandlingNullValues.py:30} INFO - DataFrame shape: (41188, 1)
[2024-10-23T19:56:24.584+0000] {HandlingNullValues.py:60} ERROR - An unexpected error occurred during data processing: 'list' object has no attribute 'write'
[2024-10-23T19:56:24.585+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-23T19:56:24.586+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-23T19:56:24.594+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=process_data, run_id=manual__2024-10-23T19:56:17.472720+00:00, execution_date=20241023T195617, start_date=20241023T195624, end_date=20241023T195624
[2024-10-23T19:56:24.611+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-23T19:56:24.623+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T19:56:24.624+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
