[2024-10-26T07:08:42.281+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:08:42.289+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:07:04.816716+00:00 [queued]>
[2024-10-26T07:08:42.292+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:07:04.816716+00:00 [queued]>
[2024-10-26T07:08:42.292+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-10-26T07:08:42.297+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_from_gcp> on 2024-10-26 07:07:04.816716+00:00
[2024-10-26T07:08:42.303+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=379) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:08:42.304+0000] {standard_task_runner.py:63} INFO - Started process 381 to run task
[2024-10-26T07:08:42.305+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'download_data_from_gcp', 'manual__2024-10-26T07:07:04.816716+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpry6xdoh9']
[2024-10-26T07:08:42.307+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask download_data_from_gcp
[2024-10-26T07:08:42.331+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:07:04.816716+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:08:42.374+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='download_data_from_gcp' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:07:04.816716+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:07:04.816716+00:00'
[2024-10-26T07:08:42.374+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:08:42.381+0000] {DownloadData.py:31} INFO - Starting data download process
[2024-10-26T07:08:42.381+0000] {DownloadData.py:32} INFO - Starting data download process
[2024-10-26T07:08:42.382+0000] {DownloadData.py:34} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T07:08:42.382+0000] {DownloadData.py:35} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T07:08:42.382+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T07:08:42.382+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:08:42.392+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=download_data_from_gcp, run_id=manual__2024-10-26T07:07:04.816716+00:00, execution_date=20241026T070704, start_date=20241026T070842, end_date=20241026T070842
[2024-10-26T07:08:42.451+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:08:42.462+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:08:42.463+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
