[2024-10-26T07:26:14.497+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-26T07:26:14.507+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:26:13.035814+00:00 [queued]>
[2024-10-26T07:26:14.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:26:13.035814+00:00 [queued]>
[2024-10-26T07:26:14.510+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-10-26T07:26:14.515+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data_from_gcp> on 2024-10-26 07:26:13.035814+00:00
[2024-10-26T07:26:14.519+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=700) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-26T07:26:14.521+0000] {standard_task_runner.py:63} INFO - Started process 702 to run task
[2024-10-26T07:26:14.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'DataPipeline', 'download_data_from_gcp', 'manual__2024-10-26T07:26:13.035814+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/src/***.py', '--cfg-path', '/tmp/tmpc9lxhxoz']
[2024-10-26T07:26:14.523+0000] {standard_task_runner.py:91} INFO - Job 99: Subtask download_data_from_gcp
[2024-10-26T07:26:14.546+0000] {task_command.py:426} INFO - Running <TaskInstance: DataPipeline.download_data_from_gcp manual__2024-10-26T07:26:13.035814+00:00 [running]> on host 7e8a88eeae3d
[2024-10-26T07:26:14.592+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='MLopsProjectGroup6' AIRFLOW_CTX_DAG_ID='DataPipeline' AIRFLOW_CTX_TASK_ID='download_data_from_gcp' AIRFLOW_CTX_EXECUTION_DATE='2024-10-26T07:26:13.035814+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-26T07:26:13.035814+00:00'
[2024-10-26T07:26:14.592+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-26T07:26:14.598+0000] {DownloadData.py:31} INFO - Starting data download process
[2024-10-26T07:26:14.599+0000] {DownloadData.py:32} INFO - Starting data download process
[2024-10-26T07:26:14.600+0000] {DownloadData.py:34} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T07:26:14.600+0000] {DownloadData.py:35} ERROR - An unexpected error occurred: File /opt/***/config/key.json was not found.
[2024-10-26T07:26:14.600+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-10-26T07:26:14.600+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-26T07:26:14.604+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=DataPipeline, task_id=download_data_from_gcp, run_id=manual__2024-10-26T07:26:13.035814+00:00, execution_date=20241026T072613, start_date=20241026T072614, end_date=20241026T072614
[2024-10-26T07:26:14.621+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-10-26T07:26:14.633+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-10-26T07:26:14.634+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
